syntax = "proto3";

package identity;

option go_package = "identity/v1";

message ErrorDetails {
  string code = 1;
  string message = 2;
}

message PingReq {
}

message PingResp {
  string message = 1;
}

message LoginReq {
  string username = 1;
  string password = 2;
}

message LoginResp {
  string token = 1;
}

message RegisterReq {
  string username = 1;
  string password = 2;
}

message RegisterResp {
  string token = 1;
}

message RefreshTokenReq {
  string token = 1;
}

message RefreshTokenResp {
  string access_token = 1;
  string refresh_token = 2;
}

service Identity {
  rpc GetPing(PingReq) returns (PingResp);

  rpc Register(RegisterReq) returns (RegisterResp);

  rpc Login(LoginReq) returns (LoginResp);

  rpc RefreshToken(RefreshTokenReq) returns (RefreshTokenResp);
}
