// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: proto/raze.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientName    string                 `protobuf:"bytes,1,opt,name=client_name,json=clientName,proto3" json:"client_name,omitempty"`
	ClientVersion uint32                 `protobuf:"varint,2,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectRequest) Reset() {
	*x = ConnectRequest{}
	mi := &file_proto_raze_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRequest) ProtoMessage() {}

func (x *ConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raze_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRequest.ProtoReflect.Descriptor instead.
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return file_proto_raze_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectRequest) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

func (x *ConnectRequest) GetClientVersion() uint32 {
	if x != nil {
		return x.ClientVersion
	}
	return 0
}

type ConnectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectResponse) Reset() {
	*x = ConnectResponse{}
	mi := &file_proto_raze_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectResponse) ProtoMessage() {}

func (x *ConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raze_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectResponse.ProtoReflect.Descriptor instead.
func (*ConnectResponse) Descriptor() ([]byte, []int) {
	return file_proto_raze_proto_rawDescGZIP(), []int{1}
}

func (x *ConnectResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

var File_proto_raze_proto protoreflect.FileDescriptor

const file_proto_raze_proto_rawDesc = "" +
	"\n" +
	"\x10proto/raze.proto\x12\araze.v1\"X\n" +
	"\x0eConnectRequest\x12\x1f\n" +
	"\vclient_name\x18\x01 \x01(\tR\n" +
	"clientName\x12%\n" +
	"\x0eclient_version\x18\x02 \x01(\rR\rclientVersion\"0\n" +
	"\x0fConnectResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId2K\n" +
	"\vRazeService\x12<\n" +
	"\aConnect\x12\x17.raze.v1.ConnectRequest\x1a\x18.raze.v1.ConnectResponseB1Z/github.com/Su-pr007/RazeProtocol/gen/go/raze/v1b\x06proto3"

var (
	file_proto_raze_proto_rawDescOnce sync.Once
	file_proto_raze_proto_rawDescData []byte
)

func file_proto_raze_proto_rawDescGZIP() []byte {
	file_proto_raze_proto_rawDescOnce.Do(func() {
		file_proto_raze_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_raze_proto_rawDesc), len(file_proto_raze_proto_rawDesc)))
	})
	return file_proto_raze_proto_rawDescData
}

var file_proto_raze_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_raze_proto_goTypes = []any{
	(*ConnectRequest)(nil),  // 0: raze.v1.ConnectRequest
	(*ConnectResponse)(nil), // 1: raze.v1.ConnectResponse
}
var file_proto_raze_proto_depIdxs = []int32{
	0, // 0: raze.v1.RazeService.Connect:input_type -> raze.v1.ConnectRequest
	1, // 1: raze.v1.RazeService.Connect:output_type -> raze.v1.ConnectResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_raze_proto_init() }
func file_proto_raze_proto_init() {
	if File_proto_raze_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_raze_proto_rawDesc), len(file_proto_raze_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_raze_proto_goTypes,
		DependencyIndexes: file_proto_raze_proto_depIdxs,
		MessageInfos:      file_proto_raze_proto_msgTypes,
	}.Build()
	File_proto_raze_proto = out.File
	file_proto_raze_proto_goTypes = nil
	file_proto_raze_proto_depIdxs = nil
}
