// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: proto/raze.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RazeService_Connect_FullMethodName = "/raze.v1.RazeService/Connect"
)

// RazeServiceClient is the client API for RazeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RazeServiceClient interface {
	Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*ConnectResponse, error)
}

type razeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRazeServiceClient(cc grpc.ClientConnInterface) RazeServiceClient {
	return &razeServiceClient{cc}
}

func (c *razeServiceClient) Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*ConnectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConnectResponse)
	err := c.cc.Invoke(ctx, RazeService_Connect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RazeServiceServer is the server API for RazeService service.
// All implementations must embed UnimplementedRazeServiceServer
// for forward compatibility.
type RazeServiceServer interface {
	Connect(context.Context, *ConnectRequest) (*ConnectResponse, error)
	mustEmbedUnimplementedRazeServiceServer()
}

// UnimplementedRazeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRazeServiceServer struct{}

func (UnimplementedRazeServiceServer) Connect(context.Context, *ConnectRequest) (*ConnectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedRazeServiceServer) mustEmbedUnimplementedRazeServiceServer() {}
func (UnimplementedRazeServiceServer) testEmbeddedByValue()                     {}

// UnsafeRazeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RazeServiceServer will
// result in compilation errors.
type UnsafeRazeServiceServer interface {
	mustEmbedUnimplementedRazeServiceServer()
}

func RegisterRazeServiceServer(s grpc.ServiceRegistrar, srv RazeServiceServer) {
	// If the following call panics, it indicates UnimplementedRazeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RazeService_ServiceDesc, srv)
}

func _RazeService_Connect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RazeServiceServer).Connect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RazeService_Connect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RazeServiceServer).Connect(ctx, req.(*ConnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RazeService_ServiceDesc is the grpc.ServiceDesc for RazeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RazeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "raze.v1.RazeService",
	HandlerType: (*RazeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Connect",
			Handler:    _RazeService_Connect_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/raze.proto",
}
